### ISSUE TITLE
csv-preview separator setting not working for headers

### ISSUE THREAD

**Issue by TechWatching** [jjuback/gc-excelviewer#10]
Is the csv-preview separator setting taken into account also in the headers line ? It seems not to work correctly for me : all the column headers are altogether in one header of an empty column.
I change the separator to ; .

**Comment by jjuback** [comment]
I was not able to reproduce your issue on a file with semi-colon delimiters in the header/data rows. My workspace settings are as follows:
```
{
    "csv-preview.hasHeaders": true,
    "csv-preview.separator": ";",
    "csv-preview.theme": "cleandark"
}
```
If changing the settings doesn't work for you, please post a few lines of your file and I'll take a look.

**Comment by TechWatching** [comment]
Seems to be an error linked to my file. When I copy my csv file or the content to another csv file, the preview works perfectly on the resulting file even if the contents are exactly the same than with my orignal csv. I can't understand why but as it is not linked with your extension I close the issue. Nice extension by the way :)
