### ISSUE TITLE
Windows Firewall notification when opening csv file

### ISSUE THREAD

**Issue by EsbenLorenzen** [jjuback/gc-excelviewer#102]
After installing the extension and opening the first csv-file, Windows Firewall notified me, that it had blocked a connection through VSCode.

What is this related to? 
I did not allow the connection, and the extension still works as expected.

More info would be appreciated.
Can try to replicate the situation again, if more information is needed.

**Comment by jjuback** [comment]
Version 3.0.36 eliminates the localhost server that caused the firewall alert.
