### ISSUE TITLE
command 'csv.preview' not found

### ISSUE THREAD

**Issue by rsetiawan7** [jjuback/gc-excelviewer#103]
In version 2.1.30, I've error

command 'csv.preview' not found.

In 2.1.29, it's working flawless.

**Comment by Neurone** [comment]
I have the same problem too.

**Comment by marcelrsoub** [comment]
same thing here

**Comment by jjuback** [comment]
There's an issue with the webpack bundle in 2.1.30. For now, I would drop back to 2.1.29.

**Comment by Kiritow** [comment]
Same here. Disabled extension auto update and used 2.1.29 instead.
