### ISSUE TITLE
Cannot find module 'iconv-lite'

### ISSUE THREAD

**Issue by PKief** [jjuback/gc-excelviewer#104]
Hi @jjuback, currently I see the following error message in my VS Code:

![image](https://user-images.githubusercontent.com/12248527/55682226-ecf08a00-5930-11e9-926e-e041ae314ef4.png)

Just checked your dependency graph, and there's at least one module that depends on this iconv-lite module:

![image](https://user-images.githubusercontent.com/12248527/55682282-b0715e00-5931-11e9-9642-ca91ba56701d.png)

I'm using version 2.1.30 of your extension.

**Comment by jjuback** [comment]
@PKief Thanks for the PR! I just posted build 2.1.31 and all seems OK now.

**Comment by jjuback** [comment]
@PKief After further review, I no longer need the copy-paste package, so I just removed it in build 2.1.32. Back when I was using TextDocumentContentProvider and previewHtml, I needed this package to do clipboard copy, but now that I am using webviews into a local express server, I can just use the built-in clipboard functionality in the underlying grid control.

**Comment by PKief** [comment]
@jjuback Cool, sounds good! I knew that my solution in this PR would only be something like a workaround but not a proper solution.

**Comment by malipetek** [comment]
I ran a script deleting all `node_modules` folders on my mac. Then I got this error.
I went into `~/.vscode/extensions` and found folder and ran `npm i` that fixed it for meh.
