### ISSUE TITLE
Error Num String Preview

### ISSUE THREAD

**Issue by ihipop** [jjuback/gc-excelviewer#109]
example.csv
```csv
NO.STING,USERNAME
111111111111111111,TEST
```
Preview:
![image](https://user-images.githubusercontent.com/423077/58065115-274b7900-7bb7-11e9-86d3-ce2adf5ddded.png)

Why there is a `104` here ?

![image](https://user-images.githubusercontent.com/423077/58065210-8c9f6a00-7bb7-11e9-803d-8b68fc1a4c6c.png)

**Comment by MonkeyOliver** [comment]
Try to change `csv-preview.formatValues` to `never` or change `csv-preview.numberFormat` (This setting defaults to `g2`).
