### ISSUE TITLE
Excel viewer shows blank screen in vscode insider 1.38.1

### ISSUE THREAD

**Issue by coffeehat** [jjuback/gc-excelviewer#110]
I've read the issue [Excel Viewer open preview shows blank screen](https://github.com/jjuback/gc-excelviewer/issues/94), but this is different. so i put a new issue here.

# Bug description
Excel viewer shows blank screen when viewing a csv file on remote machine connected by Remote - SSH on vscode insider
![image](https://user-images.githubusercontent.com/41894967/58220014-a966a980-7d3f-11e9-8206-cca5c99d676a.png)
![image](https://user-images.githubusercontent.com/41894967/58220027-bbe0e300-7d3f-11e9-8c8c-9eb8e375eabd.png)

Someone thinks the insider version of vscode brings "fundamental change in how the JS & CSS are loaded (as they are stored on the remote system instead of the local machine)." (see [Extension doesn't work with vscode-insider: Git Graph、Edit csv.](https://github.com/mhutchie/vscode-git-graph/issues/80)). Maybe it is the cause?

# How to reproduce
## Software version
* local os: Windows_NT x64 10.0.17763
* remote os: Ubuntu 16.04.1
* vscode: 1.35.0-insider (system setup) 2019-05-24T21:28:41.464Z
* vscode extensions
    * Remote - SSH: 0.37.0
    * Excel viewer: 2.1.32
## Steps
1. Install vscode insider and install Remote - SSH
2. Open an ubuntu remote machine using Remote - SSH
3. Install Excel viewer, it will automatically installed on to the remote side
4. Create a new csv file on the remote, write something, and use Excel viewer to view it

Then u can see the what i encountered.

I believe the os version is not correlated, under other os version the bug may also be reproduced.

## Notice
Sometimes on the first run after installation of insider, the excel viewer works well. But when u close and reopen the insider, the bug will emerge

**Comment by davefollett** [comment]
I'm also seeing this blank screen issue with Remote - SSH

* Local OS: Win10 Pro 1903
* Remote OS: RHEL 7
* vscode: 1.36-insider (user)
* vscode extensions:
  * Excel Viewer 2.1.32
  * Remote - SSH 0.42.2

**Comment by davefollett** [comment]
Its also not working with the following:
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

Remote OS: RHEL7
Remote - SSH 0.42.2

**Comment by magic-lantern** [comment]
Any update on this? I'm running Version 1.38.1, so several versions newer the the OP, but still having the same problem. Running 'CSV: Refresh' and 'CSV: Clear Preview State' have no effect.

**Comment by GuybrushX** [comment]
Having the same problem with Remote-SSH to an Ubuntu machine. Looks like it can't load the wijmo stuff?

Ubuntu 16.04:
Linux hostname 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

VS Code:
Version: 1.39.0-insider (user setup)
Commit: a655c0836de8b8e06f4d56fa4e581b0ced53f56f
Date: 2019-10-03T05:36:55.111Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Excel Viewer Extension:
Name: Excel Viewer
Id: grapecity.gc-excelviewer
Description: View Excel spreadsheets and CSV files within Visual Studio Code workspaces.
Version: 2.1.32
Publisher: GrapeCity
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer

Developer Webview shows the following errors:
wijmo.theme.cleandark.min.css:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
wijmo.min.css:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
wijmo.grid.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
js-base64.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
csv.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
wijmo.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
wijmo.input.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
common.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
wijmo.grid.filter.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
data:text/html;charset=utf-8,<!DOCTYPE html>
<html lang%3D"en" style%3D"width%3A 100%%3B height%3A 100%">
<head>
	<title>Virtual Document<%2Ftitle>
<%2Fhead>
<body style%3D"margin%3A 0%3B overflow%3A hidden%3B width%3A 100%%3B height%3A 100%">
<%2Fbody>
<%2Fhtml>:3 Uncaught ReferenceError: wijmo is not defined
    at data:text/html;charset=utf-8,<!DOCTYPE html>
<html lang%3D"en" style%3D"width%3A 100%%3B height%3A 100%">
<head>
	<title>Virtual Document<%2Ftitle>
<%2Fhead>
<body style%3D"margin%3A 0%3B overflow%3A hidden%3B width%3A 100%%3B height%3A 100%">
<%2Fbody>
<%2Fhtml>:3
data:text/html;charset=utf-8,<!DOCTYPE html>
<html lang%3D"en" style%3D"width%3A 100%%3B height%3A 100%">
<head>
	<title>Virtual Document<%2Ftitle>
<%2Fhead>
<body style%3D"margin%3A 0%3B overflow%3A hidden%3B width%3A 100%%3B height%3A 100%">
<%2Fbody>
<%2Fhtml>:1 Uncaught ReferenceError: resizeGrid is not defined
    at onload (data:text/html;charset=utf-8,<!DOCTYPE html>
<html lang%3D"en" style%3D"width%3A 100%%3B height%3A 100%">
<head>
	<title>Virtual Document<%2Ftitle>
<%2Fhead>
<body style%3D"margin%3A 0%3B overflow%3A hidden%3B width%3A 100%%3B height%3A 100%">
<%2Fbody>
<%2Fhtml>:1)

**Comment by thesofakillers** [comment]
#108 supposedly fixes this, hopefully the pull request gets merged soon

**Comment by jjuback** [comment]
Fixed in version 2.1.33.
