### ISSUE TITLE
CSV Preview Resize Columns Not Working

### ISSUE THREAD

**Issue by Jonnokc** [jjuback/gc-excelviewer#113]
When setting "csv-preview.resizeColumns:": "all", the previewer is not resizing columns.

Extension Version 2.1.32
settings: "csv-preview.resizeColumns": "all",

![resize-columns](https://user-images.githubusercontent.com/16293609/62217989-3302ab00-b371-11e9-90f8-febdf9f26fc1.PNG)

**Comment by jjuback** [comment]
Fixed in version 3.0.37.
