### ISSUE TITLE
[Feature Request] Jump to the end after refreshing

### ISSUE THREAD

**Issue by michael-724** [jjuback/gc-excelviewer#115]
Hi. Thank you very much for this extension. I use it to read csv log files created by my own applications during development. It's a nice and clear way to view log entries with columns using the CSV Preview.

The only thing that bothers me is that after each refresh I have to scroll down to the bottom of the file manually.

Can you create an option that automatically jumps to the end after refresh?

Thank you for sharing this beautiful and useful extension.

**Comment by moshfeu** [comment]
Could be done by adding [`retainContextWhenHidden: true`](https://code.visualstudio.com/api/extension-guides/webview#retaincontextwhenhidden) to 

https://github.com/jjuback/gc-excelviewer/blob/a4f0a119a5e29c3be91663409be929c470339fe9/src/basePreview.ts#L30-L34

**Comment by jjuback** [comment]
Fixed in version 3.0.36.
