### ISSUE TITLE
blank screen in remote-ssh environment

### ISSUE THREAD

**Issue by manipulative** [jjuback/gc-excelviewer#118]
Hi~ 
Excel Viewer works well on my laptop. But when I connected to my PC using the remote-ssh extension, it didn't work. Does anyone know how to fix it?
The version of excel viewer is 2.1.32. My laptop is macOS and my PC is win10.

**Comment by thesofakillers** [comment]
I think https://github.com/jjuback/gc-excelviewer/pull/108 fixes this, just waiting on whoever is responsible to approve the pull request

**Comment by jjuback** [comment]
Fixed in version 2.1.33.
