### ISSUE TITLE
Hope you're not kind-of, very slightly, almost unnoticeable mining me! Are you?

### ISSUE THREAD

**Issue by ruifortes** [jjuback/gc-excelviewer#123]
"This extension no longer requires access to an external CDN, which prevented it from being used behind a firewall." says the readme.

So, why is it still triggering firewall alert?

Hope you're not kind-of, very slightly, almost unnoticeable mining me!
Are you?

**Comment by jjuback** [comment]
Prior to version 2.0 (December 2017), the extension referenced CSS/JS files from cdn.wijmo.com, which is what the readme is referring to. Starting with version 2.0, those files are installed locally, and the extension opens a local web server on a random port. I have not verified this, but I suspect that the use of localhost is enough to trigger a firewall alert.

**Comment by jjuback** [comment]
Version 3.0.36 eliminates the localhost server that caused the firewall alert.
