### ISSUE TITLE
not support \n value

### ISSUE THREAD

**Issue by fjqingyou** [jjuback/gc-excelviewer#124]
```
\n display &#10;
```

**Comment by jjuback** [comment]
Can you provide more information or a screen shot? Thanks.

**Comment by fjqingyou** [comment]
@jjuback 
![test1](https://user-images.githubusercontent.com/31087168/82123099-0ddd0d00-97ca-11ea-922b-9872d17511cf.png)

**Comment by jjuback** [comment]
I tried to reproduce your issue but I'm seeing correct line breaks. Can you upload your xlsx file?

**Comment by fjqingyou** [comment]
@jjuback 

[test.xlsx](https://github.com/jjuback/gc-excelviewer/files/4662272/test.xlsx)

**Comment by jjuback** [comment]
@fjqingyou This is fixed in version 3.0.44.
