### ISSUE TITLE
Simple question. Please, why Windows Firewall asked to allow connection when I clicked for the first time "Open Preview"?

### ISSUE THREAD

**Issue by imvieira** [jjuback/gc-excelviewer#125]
Hello,

Simple question. Please, why Windows Firewall asked to allow connection when I clicked for the first time "Open Preview"?

I downloaded and installed the extension using the visual code studio.
Then, I clicked on "Open Preview" to open a file .xlsx.
However, I was asked to allow a firewall connection coming from the Visual Code Studio.
Then, I clicked on Cancel because I saw in the behind of the "prompt" that the file could be previewed in the visual code studio. 
That means I have not allowed the firewall request from my computer.

Please, I wanted to make sure what was the reason that the firewall was asked when I clicked "Open Preview", even if I have had installed before that extension?

**Comment by jjuback** [comment]
The extension opens a local web server on a random port, which is probably what is triggering the firewall alert. Still investigating.

**Comment by jjuback** [comment]
Version 3.0.36 eliminates the localhost server that caused the firewall alert.
