### ISSUE TITLE
It is not remembering its last scroll position when switching between tabs

### ISSUE THREAD

**Issue by denis-reichelt** [jjuback/gc-excelviewer#126]
Everytime I switch between different tabs, when I reactivate the preview window of a CSV file, the scroll position is at the top of the window. 
As I saw in the description, the scroll position should be something that is stored and remembered. 
Do I have to set some special setting for that?

**Comment by jjuback** [comment]
Version 3.0.36 now preserves scroll position and selected cells when switching between tabs.
