### ISSUE TITLE
A colored border line appears

### ISSUE THREAD

**Issue by project-flower** [jjuback/gc-excelviewer#129]
A colored border line appears when the network is blocked by a firewall.

Reinstalling does not help.

![image](https://user-images.githubusercontent.com/12604087/83518438-683dd380-a515-11ea-9500-c128feeef139.png)

VSCode Ver.1.45.1 (System Installed)
Excel Viewer Ver.2.1.35

**Comment by jjuback** [comment]
There are two issues here, both fixed in version 3.0.36. The localhost server was removed, so you should no longer get a firewall alert. Theme support was tweaked to use a more subtle color for cell borders, but the colored border for the entire display is used when the extension has focus.
