### ISSUE TITLE
Unable to preview Japanese excel file

### ISSUE THREAD

**Issue by ayatokura** [jjuback/gc-excelviewer#130]
My Excel file which cell contains Japanese could not be previewed properly.  Thanks. 

[VS Code environment - macOS]
version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

[VS Code environment - Windows 10]
version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

[VisualStudioCode_Translation_Japanese.xlsx](https://github.com/jjuback/gc-excelviewer/files/4808781/VisualStudioCode_Translation_Japanese.xlsx)

**Comment by jjuback** [comment]
Thank you for your prompt response. When I open your .xlsx file in Excel, the first 29 rows are blank:

<img width="496" alt="ExcelBlankRows" src="https://user-images.githubusercontent.com/18399724/85215041-f0f3a680-b340-11ea-9ed9-8c65e28e18f9.png">

In the extension, if I scroll to row 30, I see Japanese characters:

<img width="604" alt="ExtensionJapaneseCharacters" src="https://user-images.githubusercontent.com/18399724/85215057-213b4500-b341-11ea-8cbb-9422c3ce02ac.png">

I don't see anything wrong here.

**Comment by ayatokura** [comment]
For some reason I didn't notice that there were some blank line when I created this new file. I confirmed it works great.
Thank you again.
