### ISSUE TITLE
[Feature Requests] Setting to automatically open in preview

### ISSUE THREAD

**Issue by Minituff** [jjuback/gc-excelviewer#131]
I really like this plugin. I was digging through the settings and I cannot find the option to automatically open the csv or excel file in preview mode just by double-clicking on it.

Currently, I can _right click_ the file and select -> _Open Preview_ or I can click the icon at the top right.

I would love to be able to have the preview open as the default and use that same icon to switch back to the text view if possible.

Thanks.

**Comment by JaiMistry** [comment]
I would also appreciate this feature.

**Comment by jjuback** [comment]
@Minituff @JaiMistry The extension APIs do not provide a way to customize double-click behavior. For example, if you double-click a markdown (.md) file, it opens the standard editor, not the preview.

The markdown preview does have a "return to source" button, so I'll keep this issue open.

**Comment by rkief** [comment]
Is there a way to use code-runner to open the preview?
"code-runner.executorMap": {"csv": "$dir$fileName < open_preview"}
Ultimately I am looking to pipe the return of an SQL call to open in preview:
"sql": "cat $dir$fileName | isql -v <system> -b -d, -c -q > $dir$fileNameWithoutExt.csv | $dir$fileNameWithoutExt.csv < open_preview"

**Comment by lmovse** [comment]
For markdown, now i can do this with below setting in `setting.json`
```json
"workbench.editorAssociations": {
    "*.md": "vscode.markdown.preview.editor"
},
```
so , is there a way to with excel?

**Comment by jjuback** [comment]
Version 4.0.45 now supports custom editors, so you can do the same with CSV/Excel files:
```
"workbench.editorAssociations": {
    "*.csv": "gc-excelviewer-csv-editor",
    "*.xlsx": "gc-excelviewer-excel-editor"
},
```
For Excel files, the custom editor association is the default. For CSV files, VS Code's built-in editor remains the default, but you can change that if desired.
