### ISSUE TITLE
"Too small to preview: Showing the original file instead" is confusing

### ISSUE THREAD

**Issue by yilmazdurmaz** [jjuback/gc-excelviewer#132]
hey there, newly met and installed; nice extension, great work.

having 2 preview item in the menu is confusing enough, and this "Preview big CSV:head" one in the title makes confusion even further so that I thought the extension is not working for a few try.

I am guessing your intention for this second item is to take 100 or 1000 items from very big data file and show it in the preview. 

nice thinking but wrong implementation in my opinion. It should preview the content whether or not the file is big enough, then tell users use this menu item if their file is bigger sized than your magically defined number of lines (plus "I understand. don't show this again"  button and corresponding setting).

cheers

PS: short cut to open preview is not for all of us. there are people like me spending most of time browsing/reading code and using mouse most of the time and staying away the keyboard. so the context menu items are really important

PS 2: I could not find any settings to change what makes a file big, so the magic. remember, definition of big can differ with the speed of  computer we use.

**Comment by jjuback** [comment]
@yilmazdurmaz I think you must have an extra CSV extension installed. This one adds the standard "Open Preview" command to the context menu, with keyboard shortcut, just like the built-in markdown extension. It does not consider any file "too small to preview."

The only file size limitation this extension has is the "50 MB" limit imposed on all extensions by VS Code itself. See #49 for details.

**Comment by yilmazdurmaz** [comment]
@jjuback  you are right. 

I seem to got caught by an unexpected behavior from another extension, namely Rainbow CSV.  Since it was an extension just for the syntax, I didn't think that preview menu item would belong to it.
