### ISSUE TITLE
install v3.0.37 preview display invalid wijmo license.

### ISSUE THREAD

**Issue by ldh0227** [jjuback/gc-excelviewer#134]
My VSCode version is 
Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

When I preview some csv below image is shown.
![image](https://user-images.githubusercontent.com/946434/87401408-0c2a9c80-c5f5-11ea-95c0-9c0526f9df39.png)

![image](https://user-images.githubusercontent.com/946434/87401459-1d73a900-c5f5-11ea-9e41-dec7618b5a56.png)

How can I change my extensions name CLSID to gc-excelviewer?

**Comment by gennaro-tedesco** [comment]
I confirm I am seeing the same error.

**Comment by jjuback** [comment]
@ldh0227 @gennaro-tedesco This is fixed in version 3.0.38. VS Code version 1.47 changed the way webviews are hosted, resulting in a licensing nag screen.
