### ISSUE TITLE
The "CSV: Clear Preview State" setting doesn't work

### ISSUE THREAD

**Issue by yiannis-had** [jjuback/gc-excelviewer#136]
I filter and sort my csv file and then when i clear preview state it is still the same.

I've only got `"csv-preview.formatValues": "never"` in my settings.json.

**Comment by jjuback** [comment]
I haven't been able to reproduce this. Can you tell me which version of VS Code and the extension you are using? Also, are your settings for user or workspace?

**Comment by yiannis-had** [comment]
Never mind, it is working properly. I didn't realize you need to have the current preview in the foreground, I thought it does this for all the csv files in the workspace
