### ISSUE TITLE
TSV separator

### ISSUE THREAD

**Issue by denishowew** [jjuback/gc-excelviewer#139]
[The blurb](https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer) claims that:
> For .tsv and .tab files, a tab delimiter is assumed.

but, unless I change the `csv-preview.separator` setting from `,` to `\t` manually, commas are assumed in a TSV file called store.tsv, with language mode in the bottom right corner showing "TSV".

Excel Viewer v3.0.39, VSCode 1.48.0, MacOS 10.14.6

**Comment by jjuback** [comment]
I can confirm that this is a regression. Still investigating.

**Comment by jjuback** [comment]
Fixed in version 3.0.40.
