### ISSUE TITLE
Show settings in "Extensions" region of the "Settings" view of VS Code

### ISSUE THREAD

**Issue by fubar-coder** [jjuback/gc-excelviewer#144]
It would surely increase the visibility for the options, and maybe provide even better information about the setting values for - for example - `csv-preview.lineNumbers`.

**Comment by jjuback** [comment]
You can view the settings in Extensions view under Feature Contributions:
![ExtensionSettings](https://user-images.githubusercontent.com/18399724/130106907-1f757fa8-c6ce-495b-9d52-ac5301d0e744.png)

Or, you can view them in Settings view under Extensions -> Excel Viewer 
![SettingsExtensions](https://user-images.githubusercontent.com/18399724/130106950-baef25fb-f7ce-4200-8447-1de4aaf8d9f0.png)
