### ISSUE TITLE
feature request - support for .xls files

### ISSUE THREAD

**Issue by soliujing** [jjuback/gc-excelviewer#148]
currently it supports `.xlsx` files perfectly, but not for `.xls`
The "open preview" context menu didn't show up for `.xls` files.

![Screen_0106_1000-22](https://user-images.githubusercontent.com/46142545/103720292-00e58600-5006-11eb-994f-983480d7d8eb.jpg)

**Comment by jjuback** [comment]
The underlying grid control only supports `.xlsx` files, and at this point there is no chance that `.xls` will ever be supported.
