### ISSUE TITLE
cant search through table. really sucks

### ISSUE THREAD

**Issue by abdullzz** [jjuback/gc-excelviewer#149]
devs should try the searching feature. you cannot search what's not visible on the page. especially if you have a long table it's really frustrating

**Comment by JBuursma** [comment]
It works for me. I'm going to guess that your problem would be easier for the developer(s) to track down if you could make available a minimum reproducible example (a sample file as well as steps to reproduce with that file).

**Comment by jjuback** [comment]
Duplicate of #88, which remains open.
