### ISSUE TITLE
can't preview the xls and csv files

### ISSUE THREAD

**Issue by WLswert** [jjuback/gc-excelviewer#15]
hi ,I install the ext ,but it can't preview the .xls and .csv files!

the console error>  [Embedded Page] Uncaught ReferenceError: wijmo is not defined.

what shoud i do?
![qq 20170328122646](https://cloud.githubusercontent.com/assets/12693684/24389165/163b7bca-13b2-11e7-9496-19c5ed9edefd.png)

**Comment by jjuback** [comment]
Maybe a firewall is preventing you from accessing the CDN. In VS Code, run the Open File command and try to open this URL: http://cdn.wijmo.com/5.20162.198/styles/wijmo.min.css
If that fails, then that explains the reference error.

**Comment by cedricporter** [comment]
I have the same issue. 

I live in China and the GFW blocks wijmo.com. The gc-excelviewer works only when I put wijmo.com in my proxy.

I think it should tell us the error message when error occurs rather than give us an empty result.

**Comment by jjuback** [comment]
This is fixed in version 2.0.16.
