### ISSUE TITLE
Please update the Wijmo License

### ISSUE THREAD

**Issue by jebinphilipose** [jjuback/gc-excelviewer#150]
On the preview page, it gives this message - "The Wijmo license in this application has expired. The license expiration date is 2/1/2021". There is also a sticky toast message at the bottom of the preview page.

Screenshot - https://ibb.co/qW2Pn6N

**Comment by jjuback** [comment]
Working on it. Will post here when an update is available.

**Comment by jjuback** [comment]
Version 3.0.41 is now available. Removed expiration message. No other changes.
