### ISSUE TITLE
Shows old content in preview for changed csv

### ISSUE THREAD

**Issue by kapulkin** [jjuback/gc-excelviewer#155]
If I open a csv and it's preview, later I will see the same content in a preview, which was the first time. I could change csv file in any way, close/open csv or preview. I even reinstalled the plugin. The content in preview remains the same. Only file renaming helps to see the updated content in a preview.

How to reproduce
1. Open a csv file
2. Open a preview for it
3. Close the preview
4. Change the csv file content
5. Open the preview again - you will see csv content before the change.

**Comment by aziereis** [comment]
I have the same issue as @kapulkin but not with the content itself but only the header of my CSV. So the changed content is updated accordingly but the changes in the header are not. Deleting the file doesn't help but renaming does. A bug?

**Comment by jkrigelman** [comment]
Same exact issue as @aziereis . Seems like the previewer has memory to it for filters and sorting. I'm guessing that this is locking in the header information as well. When the file is refreshed or the preview reopened it doesn't seem to understand that the headers have moved, added, or were removed.

**Comment by dpelaez10** [comment]
Having the same issue. Using the workaround (CSV: Clear Preview State) for now, but would be nice to not have to do this every time.

**Comment by inwenis** [comment]
same issue

**Comment by jjuback** [comment]
@kapulkin @aziereis @jkrigelman @dpelaez10 @inwenis This is fixed in version 3.0.43.
