### ISSUE TITLE
well, when I change the first row of my csv file, the header didn't change.

### ISSUE THREAD

**Issue by Hou-Xiaoxuan** [jjuback/gc-excelviewer#168]
It seems that the the plug-in has cache the preview file and didn't change the header(the other part of the file will get the change)
Also, if I sort the preview file, how can I redo the change?  Every timeI open the preview, I see the result after sort, but I want the order of the source file.
![image](https://user-images.githubusercontent.com/59465493/129596737-b820307c-2ef2-4de3-965d-d5a53046d2b2.png)
![image](https://user-images.githubusercontent.com/59465493/129596771-6714eb98-7bd7-48bc-bd2e-63b1e01782a7.png)

**Comment by jjuback** [comment]
Version 3.0.43 fixes the issue where persistent previews don't respect changes to column structure in the underlying file.
Also, to restore the original sort order, hold the Ctrl key while clicking the header for a previously sorted column. Or, execute the command `CSV: Clear Preview State` to remove all sort/filter criteria.
