### ISSUE TITLE
Add support for cells with line break

### ISSUE THREAD

**Issue by callamaris** [jjuback/gc-excelviewer#17]
Hi,

please add support for cells with line break.

Example:
```
"a1";"b1";"c1"
"a2";"my long text
with line
breaks";"c2"
"a3";"b3";"c3"
```

Settings:
```
    "csv-preview.quoteMark": "\"",
    "csv-preview.separator": ";",
```

**Comment by jjuback** [comment]
Fixed in version 2.0.19. Multiline cells are displayed on one line in the preview, but they are now parsed correctly.
