### ISSUE TITLE
Option to stop sorting

### ISSUE THREAD

**Issue by douira** [jjuback/gc-excelviewer#171]
When I click a table header it sorts the table by that table header ascending or descending. However, when I want to go back to the original order with no sorting applied there's no option to do so in the GUI.

**Comment by jjuback** [comment]
Hold the Ctrl key while clicking the column header to restore its original sort order. You can also use the `CSV: Clear Preview State` command to remove all sort/filter criteria for the current file.

**Comment by douira** [comment]
Thanks for the info. Is this documented somewhere? I had a hard time finding anything on this.

**Comment by jjuback** [comment]
It's mentioned in the change log, but it's kind of buried as the feature was added around 3 years ago. I should add an FAQ and/or key binding section to the readme. Thank you for the suggestion.

**Comment by douira** [comment]
Good idea! Thanks for responding to my issue and taking the time to improve documentation.
