### ISSUE TITLE
Enable your extension to run on VS Code on the web 

### ISSUE THREAD

**Issue by isidorn** [jjuback/gc-excelviewer#175]
:wave: I'm Isidor, a PM from the VS Code team, and we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

We'd like to ensure Excel viewer can run in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

Please let us know if you have questions or feedback on enabling your extension for the web - our team would love to learn from your experiences and collaborate. Thank you!

**Comment by jjuback** [comment]
I'm almost ready to release a version that supports VS Code for the Web (and adds read-only custom editor support as well). I just need to do some more testing and update the readme file. I'll reply here when it's available.

**Comment by isidorn** [comment]
@jjuback great news, thanks a lot for working on this 👏

**Comment by jjuback** [comment]
@isidorn The latest version (4.0.45) now supports VS Code for the Web.

**Comment by isidorn** [comment]
Awesome 🎉
