### ISSUE TITLE
Question: How do I open an Excel file in preview mode by default?

### ISSUE THREAD

**Issue by sualeh** [jjuback/gc-excelviewer#176]
Very useful extension, since I use VS Code for my day-to-day document editing as well as coding.

How do I open an Excel file in preview mode by default? For example, for Markdown, I have the following settings:

```json
{
   ...
  "settings": {
    ...
    "workbench.editorAssociations": {
      "*.md": "vscode.markdown.preview.editor",
      "*.xlsx": ?? "grapecity.gc-excelviewer.preview"
    },
  }
}
```

**Comment by jjuback** [comment]
This is possible in the latest version (4.0.45). See https://github.com/jjuback/gc-excelviewer/issues/131#issuecomment-983261829.
