### ISSUE TITLE
It deserves a better UI

### ISSUE THREAD

**Issue by neilsustc** [jjuback/gc-excelviewer#18]
It's an amazing extension, but it looks a little old fashioned 😅.

The picture shown in FlexSheet website looks pretty good

![flexsheet](http://wijmocdn.azureedge.net/wijmositeblob/wijmo-theme/images/flexsheet-formula-support.png)

Why does it seem to be different in the vscode?

![image](https://cloud.githubusercontent.com/assets/7588612/25610385/dcba3f80-2ed7-11e7-8738-71efb7daf3df.png)

**Comment by jjuback** [comment]
The current color scheme was chosen to complement the default dark color theme of VSCode. You can change it with the `csv-preview.theme` setting. Visit this [demo page](http://demos.wijmo.com/5/Angular/Explorer/Explorer/#/grid/intro) to see the available themes.

**Comment by neilsustc** [comment]
Great!
And there is another little question. Is it a bug that the A1 cell is always highlighted?

**Comment by jjuback** [comment]
Yes. It looks like an old workaround I put in is no longer needed, so that's an easy fix.

**Comment by jjuback** [comment]
Fixed in version 1.1.15.
