### ISSUE TITLE
Csvs escaped with quotes render with the quotes visible in Preview Mode

### ISSUE THREAD

**Issue by sjd2021** [jjuback/gc-excelviewer#182]
I believe I've properly escaped the quote here as it looks fine in Google Sheets/Excel.

CSV content:
```
Code,Money1,Money2
NS,$23","785.46,$13","962.76
```

Preview:

![image](https://user-images.githubusercontent.com/84007094/149836657-3b422199-d4fa-412e-8600-bc49dca206e3.png)

**Comment by jjuback** [comment]
I can reproduce the behavior in VS Code, but I don't get the desired results in Google Sheets:
![Google182](https://user-images.githubusercontent.com/18399724/149838847-1883b025-0ad2-4060-88b7-3322e33d86ef.png)

Or in Excel:
![Excel182](https://user-images.githubusercontent.com/18399724/149838859-94ce7667-c1c8-4a6e-97b0-6d9eda82742e.png)

To get the proper display in all three apps, I would enclose the entire field in quotes, not just the comma separator:
```
Code,Money1,Money2
NS,"$23,785.46","$13,962.76"

**Comment by sjd2021** [comment]
I stand corrected. I'm not sure what's going on but I have real examples that are working annnd as I type this I now realize that they just had no commas. I originally wrapped them all in quotes but thought that wasn't quite working when I also tried to escape my double quotes. Big brain fart on my behalf.. sorry guys.
