### ISSUE TITLE
License expired

### ISSUE THREAD

**Issue by watch24hrs-iiitd** [jjuback/gc-excelviewer#186]
Hi!
Thanks for the amazing extension!
Although upon the preview of CSVs, I am additionally getting the following message:
![image](https://user-images.githubusercontent.com/55681240/157297591-b02f8719-7424-4dbd-8ad0-d16fd72fdd87.png)

**Comment by jjuback** [comment]
We are aware of this issue and will post an update as soon as we can.

**Comment by jjuback** [comment]
Fixed in version 4.2.53.
