### ISSUE TITLE
When ExcelViewer is set to default for CSV it doesn't work correctly

### ISSUE THREAD

**Issue by PrzemyslawKlys** [jjuback/gc-excelviewer#187]
I'm using ExcelViewer and it's great. However when you change the defaults of opening CSV to always open up in ExcelViewer by default

Source:
![image](https://user-images.githubusercontent.com/15063294/159112598-883abfe0-9fb6-43b9-ade2-4336083d1171.png)

After enabling to open up as default:
![image](https://user-images.githubusercontent.com/15063294/159112589-14c13bb4-f89d-4ca9-a06d-8706e7e4458b.png)

If you don't enable default and just right click "Open with"

![image](https://user-images.githubusercontent.com/15063294/159112626-01adcf58-3603-4bd9-a41f-e65f3cdf23e5.png)

**Comment by jjuback** [comment]
Here's the problem: The `separator` setting takes a regular expression, so the `,;` characters need to be enclosed in square brackets. This example is covered in the README file.

**Comment by jjuback** [comment]
The new editing code does not properly handle regex separators. Reopening the issue.

**Comment by jjuback** [comment]
Fixed in version 4.2.54.
