### ISSUE TITLE
Preview is not refreshing - stale data

### ISSUE THREAD

**Issue by byggwir** [jjuback/gc-excelviewer#19]
VS Code 1.12.1 and Windows 10 Pro:
I have a csv file that I once opened in preview. After that I changed the csv file and added a new column at position 2 from the left (so essentially a new column was added after the first column from the left).
But the preview does not show any changes.
This happens only to one file and since then no matter what I update it does not change.
So it is not reproducible with other files and I cann't fix it as I don't know what to delete.
For tests editing the csv is done in parallel in notepad++.

VS Code handels the update of the csv correctly but not for preview. Switching from the updated csv to preview works (!) for all other files except this one.
What has to be deleted that the preview is done correctly again?

Ann: The issue persists between restarts of VSCode and Windows.
In case it matters. The csv was created using Excel but the csv that works is a copy of this csv.
So I guess this is a one time issue and once I delete whatever leftover temp file there is it might work again.
Where do I find the temp files?
Deleting the %temp% folder did not work.

Deleting the file and recreating it did not work either ! It still has the old output.
There is a *.xlsx file of the same name but different extension in the folder.

**Update:** Just found out some more. This happens if I reorder a column (Possibly if I do other "editing" as well). After that it does not update the preview anymore. And I don't know how to get it to reload

**Comment by jjuback** [comment]
The extension automatically saves column layout info on a per-file basis (widths, sort/filter criteria). So if you add a new column, it won't appear when the old layout is reapplied, as you discovered. However, you can clear the saved layout by opening the preview for the file in question and then running the command `CSV: Clear Preview State`. Then close and reopen the preview and the new columns should now be visible.

**Comment by byggwir** [comment]
I see. If that is how it is defined, ok.
A bit easy to overlook changes as there isn't even a hint of new data availabe.
