### ISSUE TITLE
Feature request: preview selected text

### ISSUE THREAD

**Issue by neilsustc** [jjuback/gc-excelviewer#21]
A data file type `.arff` (used by [Weka](https://en.wikipedia.org/wiki/Weka_(machine_learning))) has this format

```
@relation ...
@attribute ...
...

@data
1,11,2,22
33,3,44,4
...
```

If we can select only the data text, right click it and click 'Preview as CSV', it would be great.

**Comment by jjuback** [comment]
As of version 2.0.20, you can achieve the same effect using the following settings:

```
"csv-preview.commentCharacter": "[%@]",
"csv-preview.skipComments": true,
"csv-preview.hasHeaders": false
```
Lines starting with a percent sign or the @ symbol will be excluded from the preview (as will empty lines). Just use the `CSV: Open Preview` command as you normally would on the entire file, without making a selection.
