### ISSUE TITLE
Setting for commenting out lines in csv

### ISSUE THREAD

**Issue by roadrunnerlenny** [jjuback/gc-excelviewer#24]
In my application, I have sometimes csv-files which have rows that are "commented out" - e.g.  every line starting with # is skipped by the csv-Reader. This comes in very handy when manipulating data directly in the file - in order to have a row not further processed, I just add a # at the beginning of the row.

For example: 

#This csv has a comment at the top which won't be processed
Header1,Header2
Value1, Value2
#Value3, Value4   <-- This line won't be processed
Value5, Value6

When using the preview function is VSCode for these csv files, the preview is corrupted because of the misinterpret header line. 

Is is it possible to add this functionality, perhaps by having additional settings like "AllowComment=true" and "CommentChar='#'"?

**Comment by jjuback** [comment]
This feature has been added in version 2.0.20. See the changelog for the names of the settings and additional documentation.

**Comment by roadrunnerlenny** [comment]
Great, thanks!
