### ISSUE TITLE
Update Repository?

### ISSUE THREAD

**Issue by Willowlark** [jjuback/gc-excelviewer#27]
The readme appears to say that there newest version of the extension is 1.1.19. The Visual Studio Code marketplace shows 1.1.15, and this repository changelog goes to 1.1.13. Where's the most recent version available?

**Comment by jjuback** [comment]
The latest version is 1.1.15. This is reflected in the changelog (whether viewed from the Extensions pane in VSCode or the GitHub site). I do not see any references to version 1.1.19 in the readme.

**Comment by Willowlark** [comment]
![image](https://user-images.githubusercontent.com/4207813/29428077-e0777148-8359-11e7-8cb5-50d4a6a330a3.png)

At the bottom of the readme. I'm having that issue with the extension which is why I'm looking for this apparent version.

**Comment by jjuback** [comment]
The reference is to build 9, not 19. Specifically, that sentence refers to this note in the changelog:

> All open CSV/Excel previews now update automatically when the configuration settings are saved. Formerly, an explicit Reload Window command was required.

Are you saying that changing user or workspace settings has no effect?

**Comment by Willowlark** [comment]
It appears I misunderstood, apologizes. My issue is the preview does not update when it's source has been changed. Nothing I do can get the thing to reflect the changes in the file.

**Comment by jjuback** [comment]
OK, that's what I thought you were going to say. See the answer for issue #19. In a future update, the extension needs to check for changes in column structure and discard saved layouts when that occurs.

**Comment by Willowlark** [comment]
Yeah, that update would be helpful when you're building the csv column by column. Thanks, #19 fixes the issue.
