### ISSUE TITLE
Preview does not update upon file contents change

### ISSUE THREAD

**Issue by reggie43** [jjuback/gc-excelviewer#29]
The preview of the csv seems to always remain that of the initially previewed csv. Therefore, when I further process the csv file, add extra columns, etc. the preview is missing this information.

**Comment by jjuback** [comment]
See the answer for issue #19. In a future update, the extension needs to check for changes in column structure and discard saved layouts when that occurs.

**Comment by reggie43** [comment]
Thanks @jjuback, I have seen your comment about clearing preview state. This should help.
