### ISSUE TITLE
Define multiple delimiters

### ISSUE THREAD

**Issue by ealap** [jjuback/gc-excelviewer#30]
I was trying to add multiple delimiters (comma and semicolon) by doing
`"csv-preview.separator": [",", ";"]`

However, arrays are not accepted.

**Comment by jjuback** [comment]
Instead of an array, you should specify a regular expression character set like this:
`"csv-preview.separator": "[,;]"`

**Comment by verajosemanuel** [comment]
Not working for me.

My setting: 

> {
>     "csv-preview.separator": "[^\t]"
> }
