### ISSUE TITLE
Cannot read property '_freezeHiddenRowCnt' of undefined

### ISSUE THREAD

**Issue by xahon** [jjuback/gc-excelviewer#31]
After trying to open an `.xls` file in code `v 1.17.2` Ubuntu `16.04 lts` black screen and nothing happens

Here is output of `code` devtools 

![image](https://user-images.githubusercontent.com/18731681/31861193-4be85c6c-b76c-11e7-9924-95419e86e29c.png)

**Comment by dimmg** [comment]
+1, happening to me as well

**Comment by jjuback** [comment]
This is fixed in version 2.0.16.
