### ISSUE TITLE
Code 1.18.0 - can't preview csv file: no entry in explorer context menu

### ISSUE THREAD

**Issue by brunetton** [jjuback/gc-excelviewer#32]
Hi, 

I don't find a way to get the extension start. I opened a regular csv file and tried:
- trigger `Excel: Open preview` command. This only give me this message:
    > Use the explorer context menu or editor title menu to preview Excel files.
- explorer context menu => there's no `open preview` entry

![capture du 2017-11-13 23-25-17](https://user-images.githubusercontent.com/86322/32752653-47b9c1ca-c8ca-11e7-8111-920ecfee2c12.png)

Nothing in devtools console.
Did I missed something ?

```
$ code --version
1.18.0
dcee2202709a4f223185514b9275aa4229841aa7
$ code --list-extensions
GrapeCity.gc-excelviewer
alefragnani.Bookmarks
eamodio.gitlens
enochc.copy-relative-path
ms-python.python
ow.vscode-subword-navigation
sbrink.elm
slevesque.vscode-hexdump
streetsidesoftware.code-spell-checker
ybaumes.highlight-trailing-white-spaces
```

Thanks !

**Comment by jjuback** [comment]
See the updated animations on the readme page for the correct ways to access the extension.
