### ISSUE TITLE
Uncaught Error: Can't find end of central directory

### ISSUE THREAD

**Issue by dimmg** [jjuback/gc-excelviewer#36]
With the latest 2.0.16 update, I can access the `.xlsx` files successfully, however no luck for `.xls` documents. Opening `.xls` documents raises the following 

```
# webview.ts:135
[Embedded Page] Uncaught Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html
```

**Comment by jjuback** [comment]
Only .xlsx is supported. The references to .xls in the extension manifest and documentation need to be removed.
