### ISSUE TITLE
Pipe "|" as a separator

### ISSUE THREAD

**Issue by kekazoh** [jjuback/gc-excelviewer#41]
I've been trying to set the pipe ` | ` as my default separator, because generally I use this separator for the csv files. When I hit preview it separates each letter as a new column.
Is there anything wrong with this separator?

**Comment by kekazoh** [comment]
I answer myself, I think I found the issue.  
`var regexItems = new RegExp(`${sep}(?=(?:[^${quote}]*${quote}[^${quote}]*${quote})*[^${quote}]*$)`);`
The extension uses a regular expression in order to split the file. The fact is that the pipe acts like an or in regular expressions. I'm not too good with regex, anyone has any idea on how to solve this?

**Comment by jjuback** [comment]
In your user and/or workspace settings, escape the pipe character like this:
`"csv-preview.separator": "\\|"`
