### ISSUE TITLE
Support pipe ("|") delimited csv files.

### ISSUE THREAD

**Issue by retrospek** [jjuback/gc-excelviewer#43]
It seems the pipe ("|") character is not recognized as a separator.

**Comment by jjuback** [comment]
Separators are used in regular expressions, so you need to escape the pipe character like this in settings:
`"csv-preview.separator": "\\|"`

**Comment by maixuanhan** [comment]
This is a really nice extension but why do you let the guessing part for the users? I've almost removed the extension and fired a same bug. The extension should support "|" without making any surprise to the users or there should be a help text in the configuration section.

**Comment by jjuback** [comment]
@maixuanhan There is now a better explanation with examples at the end of the configuration section.
