### ISSUE TITLE
can't parse with "csv-preview.separator": "$"

### ISSUE THREAD

**Issue by Siyet** [jjuback/gc-excelviewer#46]
I'm trying to open a preview of the file (encoding utf-8, 6000 row, 3Kb) with the following gc-excelviewer settings:
```json
{
    "csv-preview.separator": "$"
}
```
![preview uvr_claimes csv - mgn_edo_editor_t - visual studio code 24 03 2018 12_39_17](https://user-images.githubusercontent.com/4410812/37862581-67ba7558-2f60-11e8-92c7-deafa756111e.png)

```json
{
    "csv-preview.quoteMark": "'",
    "csv-preview.separator": "$"
}
```
![preview uvr_claimes csv - mgn_edo_editor_t - visual studio code 24 03 2018 12_40_02](https://user-images.githubusercontent.com/4410812/37862582-8513ff0c-2f60-11e8-88b7-4f90c8925131.png)

```json
{
    "csv-preview.quoteMark": "",
    "csv-preview.separator": "$"
}
```
![preview uvr_claimes csv - mgn_edo_editor_t - visual studio code 24 03 2018 12_42_17](https://user-images.githubusercontent.com/4410812/37862603-cc6d859e-2f60-11e8-9a5c-5ba3d5d34037.png)

**Comment by jjuback** [comment]
Separators are used in regular expressions, so you need to escape the dollar sign character like this in settings:
`"csv-preview.separator": "\\$"`
