### ISSUE TITLE
allow to choose separator for csv files

### ISSUE THREAD

**Issue by verajosemanuel** [jjuback/gc-excelviewer#47]
You can only have one field separator active at a time (comma, semi-colon, etc) and the only way to toggle is through manually editing the configuration. If I'm opening CSV files with different separators, which I do a lot, it's a pain.

Would be very useful a way to choose separator when viewing a CSV file.

thanks.

**Comment by jjuback** [comment]
See the reply for issue #30

**Comment by verajosemanuel** [comment]
Not working as I have commas and semicolons in columns but fields are separated by tabs
