### ISSUE TITLE
Error: "Detail: Files above 50MB cannot be synchronized with extensions."

### ISSUE THREAD

**Issue by hladf** [jjuback/gc-excelviewer#49]
When I try to preview a csv file with 20mb or more (160k lines or more), the vscode show the message below and the preview don't open. (dont have any problem with the csv)

> Unable to open 'Preview 'FILE.CSV'': cannot open file:///c%3A/............../FILE.CSV. Detail: Files above 50MB cannot be synchronized with extensions.

**Detail: the csv have 21mb, not 50.**
Have any way to avoid this problem and open preview?

## Thanks for the extension, is very helpful!

**Comment by hladf** [comment]
# Solved
I'd changed the name of the file of "CT2_2018_02.CSV" to "CT2-Copia.CSV" and the preview open fine.
Why? dont know kkkk

**Comment by hladf** [comment]
## Correcting: rename don't work again.

**Comment by jjuback** [comment]
From the vscode respository, in /src/vs/editor/common/model/textModel.ts, the TextModel class defines these constants:

	private static readonly MODEL_SYNC_LIMIT = 50 * 1024 * 1024; // 50 MB
	private static readonly MODEL_TOKENIZATION_LIMIT = 20 * 1024 * 1024; // 20 MB
	private static readonly MANY_MANY_LINES = 300 * 1000; // 300K lines

The constructor checks the file size as follows:

		// !!! Make a decision in the ctor and permanently respect this decision !!!
		// If a model is too large at construction time, it will never get tokenized,
		// under no circumstances.
		this._isTooLargeForTokenization = (
			(bufferTextLength > TextModel.MODEL_TOKENIZATION_LIMIT)
			|| (bufferLineCount > TextModel.MANY_MANY_LINES)
		);

		this._shouldSimplifyMode = (
			this._isTooLargeForTokenization
			|| (bufferTextLength > TextModel.MODEL_SYNC_LIMIT)
		);

In your case, the 20MB tokenization limit is reached. However, the error message has 50MB hard coded (in /src/vs/workbench/api/electron-browser/mainThreadDocuments.ts):

		return promise.then(success => {
			if (!success) {
				return TPromise.wrapError(new Error('cannot open ' + uri.toString()));
			} else if (!this._modelIsSynced[uri.toString()]) {
				return TPromise.wrapError(new Error('cannot open ' + uri.toString() + '. Detail: Files above 50MB cannot be synchronized with extensions.'));
			} else {
				return undefined;
			}
		}, err => {
			return TPromise.wrapError(new Error('cannot open ' + uri.toString() + '. Detail: ' + toErrorMessage(err)));
		});

This is a limitation imposed by VSCode itself, and can't be fixed by an extension.
