### ISSUE TITLE
about separator

### ISSUE THREAD

**Issue by toyjack** [jjuback/gc-excelviewer#5]
Can I change separator to a tab?
I tried to use "\t" but it seems doesn't work.

    "csv-preview.separator": "\t",
    "csv-preview.quoteMark": "\"",
    "csv-preview.hasHeaders": true,
    "csv-preview.theme": "cleandark"

BTW
A very good plugin! Thank you!!!

**Comment by jjuback** [comment]
I just tested the tab separator `"\t"` with version 1.0.7 and it works as expected. However, the default behavior of VS Code is to convert tabs that you type into spaces. If you change the configuration setting `editor.insertSpaces` to `false`, then VS Code will insert tab characters.

**Comment by toyjack** [comment]
I tried again today. And it works.
Sorry for waste of your time.
