### ISSUE TITLE
Automatically detect csv's column separator through "sep" keyword

### ISSUE THREAD

**Issue by bergamin** [jjuback/gc-excelviewer#50]
The sep keyword is used to change the csv's default separator from a comma to whatever you want in software like Excel. It is quite useful when you have files that could have commas as part of the data. An example:

```
sep=~
Column 1~Column 2~Column 3
Value 1~~Value 3
~Value 2~Value 3
.
.
.
```

**Comment by jhonore** [comment]
It should detect or let the user configure it when he open the preview.

UP
+1

**Comment by bergamin** [comment]
No news on this? This is extremely needed because if your language isn't English (a.k.a. most of the planet), there is a good chance Excel has a different default (pt-BR Excel for instance, breaks columns on `;` because `,` is the decimal separator). Since we need to make software that works properly regardless of language, we need to add this config to it, so every Excel on the planet knows what to do with it and we don't have to train every user to change the separator in Excel settings.

While that's sorted out, we end up being stuck at using Excel to view these as well because this extension can't do it.

**Comment by jjuback** [comment]
Version 4.0.45 now has this feature.

**Comment by bergamin** [comment]
Thank you very much, @jjuback!
