### ISSUE TITLE
Sort by multiple columns

### ISSUE THREAD

**Issue by dhirschfeld** [jjuback/gc-excelviewer#54]
It would be very useful to be able to sort by multiple columns - i.e. sort first by one column and then sort by another.

**Comment by jjuback** [comment]
Feature added for CSV files in version 2.0.21. Ctrl+click a previously sorted column to remove all sort criteria.

**Comment by RocStone** [comment]
Holding shift key to apply a secondary column sorting is not working for me. I wonder if there is a bug?
