### ISSUE TITLE
Columns order is not preserved

### ISSUE THREAD

**Issue by brunetton** [jjuback/gc-excelviewer#55]
Hi,

I wanted to use this this extension to navigate on a [big TSV file](http://www.imf.org/external/pubs/ft/weo/2018/01/weodata/WEOApr2018alla.xls) (renamed replacing the original extension by `.tsv`) but columns order is not preserved:

![capture du 2018-04-23 12-07-41](https://user-images.githubusercontent.com/86322/39120513-f16f9288-46ee-11e8-81e6-e726e7fe9326.png)

`2023` is the before last column in file, and `WEO Country code` is the first. In the preview, `WEO Country code` (values `001` on this screenshot) is displayed on the middle.

VScode 1.22.2

Do you have an idea of what could cause this ?
Thanks !

**Comment by jjuback** [comment]
Column order is persisted on a per-workspace, per-filename basis. So if you rename a file, any column reordering performed earlier is lost. This behavior is by design.

**Comment by brunetton** [comment]
I don't think you got the point. 
I never done any colum reordering (didn't even knew it was possible). 
I just renamed the file then opened it for the first time => displayed columns order in the plugin is not the same as the original file.
