### ISSUE TITLE
Numbers are displayed with an unwanted thousand separator 

### ISSUE THREAD

**Issue by pteyssier** [jjuback/gc-excelviewer#59]
Hello,

I have a csv file with a list of machines containing columns like host, port, etc.
Using the csv preview, those ports are displayed with a thousand separator. 
Example: 8080 -> 8,080
1) I didn't find any configuration to avoid that display conversion
2) This thousand separator is arbitrary. It's not the one configured on my machine (I have no separator set)

Expected: display raw number as if they were string

OS: Mac
ExcelViewer version: 2.0.21
VScode version:1.23

Origin: https://github.com/jjuback/gc-excelviewer/commit/59dc21df0415ddb8182bb03c0ad35bd9428e7423#diff-2577ae669ba97b0f3fe6ff68f6d687a4R68

**Comment by purplekrayons** [comment]
I just installed this -- noted the same thing. The value represented, is not what it should be. In my case, the numbers in my csv represent product SKUs.

![image](https://user-images.githubusercontent.com/9218035/40307945-6f35450c-5cd2-11e8-9e48-bd091d250588.png)

Moreover, and unrelated to this topic, it fails to split records properly; note the above `42156644","KK`. Really cool idea for an extension; i'll come back once you've worked out the kinks. Keep at it though, this is promising :)

**Comment by jjuback** [comment]
@purplekrayons Can you post a few lines of your CSV so I can take a look at the line breaking issue? Thanks.

**Comment by purplekrayons** [comment]
Just an observation, note the third column:

`6" PINEAPPLE GRASS BALL`

`"42136364","KK-13352A ","6" PINEAPPLE GRASS BALL"`

Possibly related to the double quote inside the double quote? Per [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt]):

>    7.  If double-quotes are used to enclose fields, then a double-quote
>        appearing inside a field must be escaped by preceding it with
>        another double quote.  For example:
> 
>        "aaa","b""bb","ccc"

The author of my CSV files, does not appear to be escaping things properly.

Here's a few sample lines:

```
"42134885","KK-11399B-YE YELLOW","MINI TULIP BOUQUET YELLOW 13.5","","0421","MACLAW FLORAL LTD.","01"," ","41421","PLANTS","500","ACCESSORIES","1FURN","0","","","TULIP BOUQUET","",""," ","","","","","","",".00","1.00","","","17-may-2018" 
"42136364","KK-13352A ","6" PINEAPPLE GRASS BALL","","0421","MACLAW FLORAL LTD.","01"," ","41421","PLANTS","500","ACCESSORIES","1FURN","0","","","PINEAPPLE BALL","",""," ","","","","","","",".00","1.00","","","17-may-2018" 
"42151756","KK-11399B-RD RED","MINI TULIP BOUQUET RED 13.5"","","0421","MACLAW FLORAL LTD.","01"," ","41421","PLANTS","500","ACCESSORIES","1FURN","0","","","TULIP BOUQUET","",""," ","","","","","","",".00","1.00","","","17-may-2018"
```

**Comment by jjuback** [comment]
@pteyssier I made your pull request into a new setting, `csv-preview.numberFormat`, that defaults to `g2`.
