### ISSUE TITLE
Refresh and reset filter/sorting settings after switching tabs

### ISSUE THREAD

**Issue by ivoh** [jjuback/gc-excelviewer#6]
VSCode 1.40, ExcelViewer 1.1.9

When I open preview of CSV file
and I set up filter on some column or change sorting
then I **switch to different tab in VSCode and switch back** (ctrl-tab or mouse click)
then the tab with "Preview '....'" gets refreshed and **loose (got reset) all the settings like filtering and sorting**.

I would expect that it would not refresh and maintains the filtering/sorting settings until the tab is closed. This behaviour makes it impossible to continuously work on multiple open files or compare them together.

Otherwise it is very useful and cool extension.

**Comment by jjuback** [comment]
As of version 1.1.10, CSV filter/sort criteria and user-resized column widths are persisted automatically using `ExtensionContext.workspaceState`. This means that any changes made in the preview window will be saved on a per-document basis and restored when you switch back to that tab, even if you close and reopen VSCode itself.

Also note that this version adds filtering capabilities to Excel files. As with CSV, filter criteria are persisted in the same way. However, column resizings are not persisted (yet).

**Comment by jjuback** [comment]
As of version 2.0.21, filter/sort criteria and horizontal/vertical scroll bar positions are persisted automatically for both CSV and Excel files. Column resizings are persisted for CSV files only. This is a limitation of the underlying FlexSheet control used to render Excel files.

**Comment by mosakashaka** [comment]
I just found this issue.
May I know that is it possible not to refresh the Excel file after switching tab?
