### ISSUE TITLE
Trailing newlines should be ignored

### ISSUE THREAD

**Issue by Clockwork-Muse** [jjuback/gc-excelviewer#61]
CSVs with a trailing newline show an extra, empty line (at least on Windows).

For example, from the [tensor-flow sample dataset](http://download.tensorflow.org/data/iris_training.csv):
![image](https://user-images.githubusercontent.com/5569508/40396140-518f3c56-5de0-11e8-82cc-7de3c463b1ce.png)

(of course, currently VSCode shows the empty line anyways, even though from a POSIX standpoint it doesn't actually exist.)

**Comment by jjuback** [comment]
Fixed in version 2.1.23.
