### ISSUE TITLE
custom file extensions

### ISSUE THREAD

**Issue by ryenus** [jjuback/gc-excelviewer#62]
Is it possible to add custom file extensions other than the default `.csv, .tsv, .tab`?

In our project we have lots of data files using another extension due to a platform-wise convention, such a file can be previewed as expected once renamed to `.csv`, but having to rename it to view it then restoring the original extension is not something I guess everyone would like.

Probably a better way I'd like to have is, regardless whatever extension the current file has, always allow it to be previewed when the action is triggered through the command palette, hence one doesn't have to customize the supported file extensions. And it's the user's own responsibility to make sure the file is a good *"citizen"* to be previewed.

**Comment by jjuback** [comment]
You can run `CSV: Open Preview` from the command palette regardless of file extension.

**Comment by ryenus** [comment]
In case the file is a somewhat *"malformed"* csv, e.g. inconsistent number of columns, using `CSV: Open Preview` doesn't work and showed the following error:
> Active editor doesn't show a CSV or plain text document.

However, renaming the file to have a `.csv` extension then it just works.

Is it possible to make it behave the same regardless the file extension?

**Comment by jjuback** [comment]
In version 2.1.23, you should be able to run the built-in command `Change Language Mode` and select the `Configure File Extension` option to create a user setting that maps the current file extension to CSV or TSV. Alternatively, you can select the CSV or TSV language mode directly for the active editor only.
