### ISSUE TITLE
Setting for number of significant figures

### ISSUE THREAD

**Issue by zdog234** [jjuback/gc-excelviewer#65]
Hello. I'd love to be able to set the number of significant digits that are displayed (so I don't end up with 0.00 and 0 (where 0.00 is actually something like 0.00000001).

**Comment by jjuback** [comment]
Version 2.1.23 has a new setting, `csv-preview.numberFormat`. Default is `g2` (general format, 2 significant digits).

**Comment by jjuback** [comment]
See [this page](http://demos.wijmo.com/5/Angular/WijmoHelp/WijmoHelp/topic/wijmo.Globalize.Class.html) for information on supported formats. Also, you need to run the `CSV: Clear Preview State` command after changing the format since it is persisted along with other column properties.

**Comment by gennaro-tedesco** [comment]
It seems the command doesn't have any effect, namely changing the `csv-preview.numberFormat` followed by `CSV: Clear Preview State` doesn't really change the display of the figures (not even after restart).

**Comment by jjuback** [comment]
@gennaro-tedesco If you can post a few lines of your file and the settings you're trying to use I'll take a look at it.

**Comment by gennaro-tedesco** [comment]
So, I managed to have it work on Ubuntu 18.04 but somehow not on Mac. Consider the following example, say,
```
Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
5.1,3.5,1.4,0.2003,setosa
4.9,3,1.4,0.2123123,setosa
4.7,3.2,1.3,0.25133213,setosa
```
with the setting `"csv-preview.numberFormat": "g4"`. After using `CSV: Clear Preview State` I correctly see 4 significant figures in the Petal.Width column if using Ubuntu but not on Mac.

**Comment by gennaro-tedesco** [comment]
So, I managed to have it work on Ubuntu 18.04 but somehow not on Mac. Consider the following example, say,
```
Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
5.1,3.5,1.4,0.2003,setosa
4.9,3,1.4,0.2123123,setosa
4.7,3.2,1.3,0.25133213,setosa
```
with the setting `"csv-preview.numberFormat": "g4"`. After using `CSV: Clear Preview State` I correctly see 4 significant figures in the Petal.Width column if using Ubuntu but not on Mac.

**Comment by jjuback** [comment]
I tried your data on a Mac but it always works for me (for both user and workspace settings). I trust that you remembered to save the settings before switching back to the preview tab. Can you try opening the preview, then running the command `Developer: Open Webview Developer Tools`, followed by the clear state command. Are there any error messages in the console tab of the debugger?

**Comment by jjuback** [comment]
Also, on the Mac, local storage is written to:
`/Users/your-name/Library/Application Support/Code/Local Storage`
The filename will be something like `file__0.localstorage`. It's binary, but you can check the date/time to verify that the clear state command is actually doing something.

**Comment by gennaro-tedesco** [comment]
I finally got it to work: somehow I had to first delete the `file__0.localstorage` from the folder, for some reasons, and `CSV: Clear Preview State` again for it to work. By repeating this operation whenever settings changes occurr, they are correctly reflected in the preview.

So far so good then, thank you for looking into it.
