### ISSUE TITLE
Files above 50MB cannot be synchronized with extensions

### ISSUE THREAD

**Issue by Behzadkhosravifar** [jjuback/gc-excelviewer#67]
I have a heavy .csv file which is 680MB and opened easily in VS code but when I want to open it in preview mode by this extension, I get this exception:
``` 
Unable to open 'Preview 'basket tags.csv'': 
cannot open file:///d%3A/Sbu/Term2/Data%20Mining/P2/Solution/basket%20tags.csv. 
Detail: Files above 50MB cannot be synchronized with extensions..
```

Thanks 
Behzad

**Comment by jjuback** [comment]
Please see my response to issue #49. Unfortunately, this is a limitation of VS Code.

**Comment by Behzadkhosravifar** [comment]
In the [Rainbow CSV](https://github.com/mechatroner/vscode_rainbow_csv) repository (Highlight CSV and TSV files in different colors), I seen this for big files:

[Working with very big files](https://github.com/mechatroner/vscode_rainbow_csv#working-with-very-big-files)
VS Code disables rainbow syntax highlighting for very big files (more than 300K lines or 20MB), but starting from VS Code version 1.23.1 there is a workaround: add `"editor.largeFileOptimizations": false` to your VS Code settings to highlight large CSV files.

Is this option ok for your project?

Thanks for response

**Comment by jjuback** [comment]
I tried this setting, but it has no effect on my extension.
