### ISSUE TITLE
Column names are capitalized / automatically filled in

### ISSUE THREAD

**Issue by josteinbf** [jjuback/gc-excelviewer#69]
I just tried this extension today, and it looks very good. I did stumble upon these issues:

* Column names appear to be capitalized in the preview. This is undesirable, as referring to the column names in code therefore easily can cause errors. E.g. a column header of "feature" is shown as "Feature".
* A column with an empty name (first row) field is automatically labelled as "A", also when the following columns do have names. I guess assigning names to the columns make sense when there are no column names at all, but in this case I think leaving the header field blank would be preferable.

**Comment by jjuback** [comment]
For the first issue, change the setting `csv-preview.capitalizeHeaders` to false. I'll take a look at the second one.

**Comment by josteinbf** [comment]
The settings change works perfectly, thanks! To me, that is also the more important of the two bullet points.

**Comment by jjuback** [comment]
Empty column names are respected in version 2.1.28.
