### ISSUE TITLE
Copy cell from the table does not work

### ISSUE THREAD

**Issue by ido-ran** [jjuback/gc-excelviewer#70]
When I open the preview of CSV file and select a specific cell in the table I press Command+C (I use Mac) but the value is not copied into the clipboard.

**Comment by jjuback** [comment]
Clipboard copy now works on non-Windows platforms, as of version 2.1.25. Copied text has tab separators (like Excel) and Unix line endings.

**Comment by yalin** [comment]
Right-click and select "Copy" does not work on Linux (Pop OS)
_or I'm doing it wrong_
