### ISSUE TITLE
Fatal bug: auto open view when code stdin recieve data

### ISSUE THREAD

**Issue by dongzhuoer** [jjuback/gc-excelviewer#75]
when you send some string to VSCode 's stdin, like `echo 'haha' | code -`, the excel viewer will open automatically, and you can't even close it (the only solution is to open the source window, i.e., `code-stdin-gib.txt` in the example)

![image](https://user-images.githubusercontent.com/15871952/44328739-f3f78480-a494-11e8-9625-aa695c36f1ff.png)

```bash
$ code -v
1.26.1
493869ee8e8a846b0855873886fc79d480d342de
x64
```

**Comment by mgesbert** [comment]
this is currently preventing me from using this extension, which makes me sad :( Why preview `.txt` files?

**Comment by jjuback** [comment]
@dongzhuoer @mgesbert There is a new version, 2.1.26, that turns this feature off by default. Stdin preview was requested by a user on the VS Marketplace. The setting `csv-preview.openStdin` can be set to true to re-enable it.
