### ISSUE TITLE
Feature: Enable "Open Preview" when language mode is changed to compatible TSV, CSV

### ISSUE THREAD

**Issue by mpowrie** [jjuback/gc-excelviewer#77]
Please enable the "Open Preview" button to show when the "language Mode" of a file is changed to a CSV or TSV, rather than just showing the "Open Preview" button for files with certain file extensions such as .csv or .tsv.

Example Use case:
A .log file that has tab separated values does not show the "Open Preview" button from VS Code.  By enabling the tool when the "language mode" is selected as TSV, no file renaming or manual running of commands need to occur.

Thanks!

**Comment by ibraimgm** [comment]
Just did it. Take a look at PR #89.

**Comment by jjuback** [comment]
@ibraimgm PR included in version 2.1.27.
