### ISSUE TITLE
Open Preview doesn't work if the file isn't visible in the Explorer pane

### ISSUE THREAD

**Issue by The-MAZZTer** [jjuback/gc-excelviewer#80]
Reproduction:

Open a workspace, for example C:\foo.
Open a CSV file not in that workspace, for example C:\bar\file.csv. I did it from a cmd.exe window.
Click the Open Preview button on the toolbar, or right click the filename in the breadcrumb (if ensabled) and click Open Preview.

Nothing will happen, no editor is opened to display the FlexGrid. It will only work if the file is in the workspace.

**Comment by jjuback** [comment]
Fixed in version 2.1.29.
