### ISSUE TITLE
Show CSV records in natural order

### ISSUE THREAD

**Issue by The-MAZZTer** [jjuback/gc-excelviewer#86]
Right now it looks like you are sorting newly-opened files by the first column. Depending on the data, natural order (the order the records appear in the file) may be desired.

If files are getting sorted by natural order initially, there needs to be a way to return to that order.

**Comment by joellutz** [comment]
@The-MAZZTer Try holding down the Ctrl key while clicking on a column header, this should clear the sort conditions for that column. Got this from a similar issue: #53

**Comment by jjuback** [comment]
No sorting occurs unless initiated by the user. You can Ctrl-click as the previous poster suggested. On a related note, a fix is in the works for #83.
