### ISSUE TITLE
The file is not displayed in the editor because it is either binary or uses an unsupported text enconding

### ISSUE THREAD

**Issue by abelardolg** [jjuback/gc-excelviewer#91]
Open an Excel file from Explorer by using the contextual menu. 
Choose Visual Code.
It shows this message.

Which text enconding does this plugin support?

Nice project!

Cheers.

**Comment by abelardolg** [comment]
I created an Excel file by using MS Excel Office 365 in Windows 10 Pro.
VS Code: 
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Cheers.

**Comment by abelardolg** [comment]
I used the APACHE POI JAVA library in order to programmatically generate an Excel file. Then, I tried to open it with VC but it failed and this same message was showed.

**Comment by jjuback** [comment]
@abelardolg Right-click the tab and select Open Preview. A new tab will be created with the Excel preview.
