### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Evans-Okerosi** [jjuback/gc-excelviewer#93]
- Issue Type: `Performance`
- Extension Name: `gc-excelviewer`
- Extension Version: `2.1.29`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/evans/GrapeCity.gc-excelviewer-unresponsive.cpuprofile.txt`
[cpuprofile.txt](https://github.com/jjuback/gc-excelviewer/files/2899500/cpuprofile.txt)
 :warning:

**Comment by jjuback** [comment]
Try version 2.1.30, which uses webpack bundling to reduce file size and load times.
