### ISSUE TITLE
Can't preview TSVs saved with TXT extension

### ISSUE THREAD

**Issue by object01** [jjuback/gc-excelviewer#96]
I'm working with lots of .txt files that are in fact tab-separated value files, and am prohibited from changing their extension.  But I can't open these files in Excel Viewer unless I change their extension .tsv, so I have to make copies, or I have to configure VSCode to treat all .txt files as TSV, which is a workaround but seems like overkill.

**Comment by jjuback** [comment]
You can run the built-in command `Change Language Mode` to treat individual .txt files as TSV.
