### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by IvanMejico** [jjuback/gc-excelviewer#97]
- Issue Type: `Performance`
- Extension Name: `gc-excelviewer`
- Extension Version: `2.1.29`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/nemos/GrapeCity.gc-excelviewer-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jjuback** [comment]
Try version 2.1.30, which uses webpack bundling to reduce file size and load times.
